version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    volumes:
      - .:/var/www/html 
    networks:
      - my-network
    depends_on:
      - db 

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: fp_web
      MYSQL_ROOT_PASSWORD: "12345"
      MYSQL_USER: user_fp  
      MYSQL_PASSWORD: "user_password" 
    volumes:
      - db_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql 
    networks:
      - my-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8081:80" 
    environment:
      PMA_HOST: db 
      MYSQL_ROOT_PASSWORD: "12345" 
    networks:
      - my-network

volumes:
  db_data:

networks:
  my-network:
